server:
  port: 80
  context-path: /shop-mserver
  tomcat-uri-encoding: UTF-8

spring:
  redis:
    host: localhost
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    timeout: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.249.28.234:3306/wchat_shop?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


mybatis.configuration.call-setters-on-nulls: true #mybatis 返回Map 显示null
keywords_api_url: http://localhost:808
login_test: true
default:
  redirect_url: https://www.wodesh.cn:8088/pay.html
  wchat_token_open: false
  pay_callback: http://wodesh.cn/shop-mserver/rest/pay/callback
  wchat_sendmessage_user: owF-Kw_dNmnrDON7ZGz8VDP3p7k4
  wchat_sendmessage_token: 每日推送